### PR TITLE
use % formatter

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Could you please explain the rational of this PR? 
According to your recent activities on GitHub, it seems that your PR is automatically generated by a bot...

**Comment by EdwardBetts** [comment]
Not a bot, I'm doing them by hand.

**Comment by AlexandreDecan** [comment]
Then the question is: why ??

**Comment by EdwardBetts** [comment]
I just found out about the Python % string formatter. I think it is a cool feature, more people should know about it.

**Comment by AlexandreDecan** [comment]
I should agree.

**Comment by AlexandreDecan** [comment]
Merged into devel (7ffbab0)

**Pull request closed without merging**
