### PR TITLE
fix ruamel.yaml on 0.14.X for now

### PR DESCRIPTION
**Pull request by AvdN**
Thank you for using ruamel.yaml. 

There will be API changes in the 0.15+ versions, that might lead to warnings that 
your users could see. 
Therefore please release a version of your package with this change, so that it will not 
automatically take the latest ruamel.yaml release.

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Thanks for warning us. Is there any documentation on the upcoming somewhat backward incompatible changes that will be bundled with 0.15? I prefer to avoid defining an upper bound constraint on a dependency version to limit the risk of co-installability issues...

**Comment by AvdN** [comment]
These are preparations for larger changes. There is a beginning of documentation [here](http://yaml.readthedocs.io/en/latest/api.html#reason-for-api-change)

Eventually I want to get rid off (i.e. replace with a more flexible interface) the `Loader` and `Dumper` classes, and at some point before that changes that will affect subclassing their composites (Parser, Emitter, etc. not something used for everyday purposes).

Co-instability is a potential problem, but only for those installs not using separate virtualenvs for their utilities.

If you don't set the constraint, it is not that sismic will not work. When I changed `load()` to warn because it is unsafe to use, I issued the warning once per invocation, with instructions what to do (i.e. how to change the package, to suppress the warning/use a safe loader). 

For the future changes there will be at least a few weeks between warning for a particular needed change and the actual changes that might make a program fail if those warnings were ignored.

Looking at your io/yaml.py, the changes are minimal and you could already use the new interface from 0.15.0, as long as you would use dependency on yaml.versioninfo < (0, 15) to invoke the old code if older versions are installed. That would be a few extra lines, but probably worth it.

**Comment by AvdN** [comment]
[Here](http://yaml.readthedocs.io/en/latest/api.html#transparent-usage-of-new-and-old-api) are some examples on how to be able to use the old and new API at the same time. Then you can fully adapt to what another package that uses `ruamel.yaml` dictates.

**Comment by AlexandreDecan** [comment]
Fixed in 6b146f0. Thank you!!

**Pull request closed without merging**
