### PR TITLE
statechart image added

### PR DESCRIPTION
**Pull request by tommens**
I still need to iterate over the text

### CODE REVIEW

**Comment by tommens** [comment]
I do not see how I can model your version using the traditional statechart syntax: in my statechart, timer and display are parallel REGIONS (of the "active" superstate if you want). But a REGION by itself cannot own transitions (in your case, the "reset" transition with associated action "elapsed_time =0").
In your case this is possible, since you use states as a placeholder for transitions...
The only solution that I see (and that respects the statechart syntax) is either the one that I proposed, or an alternative one in which one would define the "reset" transition at the level of the top-level state "active", which is a solution that would work as well.

We should discuss if you really want to stick to your way of replacing the notion of regions by the notion of states: this solution appears to be a bit more flexible in some cases, but I wonder how this can be represented easily using a graphical visual notation. One would need to introduce a graphical way to distinguish parallel states from normal states. Perhaps the notation as used by Yakindu would do: rounded light blue rectangles for normal states; ordinary gray rectangles for parallel states. The main difference is that in Yakindu, a gray rectangle represents a region, and hence one cannot define transitions, or internal events, or entry/exit actions on them. In your solution you can, since they are "real" states...

**Comment by AlexandreDecan** [comment]
We could discuss about this, but I don't think it's a good idea to restrict Sismic modeling regions as states "just because Yakindu has no support for it", especially since Sismic acts exactly as SCXML does. 

Doesn't Yakindu support nested states in parallel regions? I don't understand why it is not possible to rename "timer" in "timer_region" and to add a "timer" state that contains "stopped" and "running". Simply add an additional intermediate state. This way, you can define a "reset" transition from "timer" to "timer"...

If needed, I can model the YAML statechart using DIA (or any other tools) to avoid being restricted to Yakindu's expressiveness.

**Comment by tommens** [comment]
I agree with you that we do not need to restrict the expressiveness because our (and SCXML notation) is indeed more flexible. Have a look at the new image in how it should be done in Yakindu. (Note that in that case, and extra region, and an extra initial state is needed, because of the fact that one needs to make an artificial difference between the parallel region timer_region and the unique state timer it is containing.)

I agree that we could/should use another diagramming tool if we do not want to be restricted to Yakindu's expressiveness. Ideally, the diagramming tool should have some kind of built-in template that makes it easy to create statecharts. I know that Visio allows this, and probably DIA does as well, but I have never checked this...

**Comment by AlexandreDecan** [comment]
The new image seems fine to me. Maybe you could add a "display_region" to be consistent?

FYI, Dia is quite rudimentary and has no direct support for statecharts. But statecharts are mainly rectangles and arrows ;-)

**Comment by AlexandreDecan** [comment]
I believe you could replace*stopwatch_statechart.png* by *stopwatch_simulated.png*. Right?

**Comment by AlexandreDecan** [comment]
Thanks for the changes! 

For the statechart graphical representation, I suggest (if you agree?) to remove all the logic in it (including ``elapsed_time += 1``) and to keep only the things that are related to the "external behavior" of a stopwatch. This way, we can use the image to illustrate what is a stopwatch timer, without making any assumption on how it is currently implemented. This should be more suitable as we provide two differents way to implement it.

**Comment by tommens** [comment]
Alternatively we could show 3 graphical representations: a generic one without any logic in it, and then a specific one for each of the two proposed solutions...

**Comment by AlexandreDecan** [comment]
Indeed. If you agree to do the additional work, please do it. 
I'll merge current PR asap, so open a new one please.

**Comment by AlexandreDecan** [comment]
@tommens could you please have a look at https://github.com/AlexandreDecan/sismic/blob/refactor-24/docs/examples/stopwatch.yaml and https://github.com/AlexandreDecan/sismic/blob/refactor-24/docs/examples/stopwatch_external.yaml

The upcoming release of Sismic includes a lot of changes, both in the ``model`` and in the YAML format. Notably, the root state of a statechart is now explicitly declared in YAML instead of using an implicit compound state. For example, this means there is not any more a need to represent a ``Statechart`` state in your graphical representation: 
https://github.com/AlexandreDecan/sismic/blob/master/docs/images/stopwatch_with_logic.png

I believe this will be easier for you to make graphical examples using Yakindu?

If it's ok for you, could you make a PR on *refactor-24* branch, so the graphical representations will be up-to-date when I'll release the new version.

**Pull request merged**
