### PR TITLE
Mutation based testing

### PR DESCRIPTION
**Pull request by aliparsai**
This is necessary for example in case of deepcopy. This way, exceptions such as KeyError are handled in the standard manner: by raising an AttributeError

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Thanks for the PR. I'm currently making a lot of backward incompatible changes in Sismic. Those changes, among other, aim to facilitate the manipulation of the structure of a statechart. This will be part of the next major update (which I plan to deploy at the end of the week).

Could you please have a look at *refactor-24* branche (https://github.com/AlexandreDecan/sismic/tree/refactor-24) and update your PR? I suggest you to have a look at the changelog, it already contains a quite exhaustive list of changes. The documentation is up-to-date too, but needs to be compiled using Sphinx. 

In particular, you'll find ``add_state``, ``remove_state``, ``rename_state``, ``add_transition``, ``remove_transition`` on ``model.Statechart``. This can help you doing mutations. 
Notice I already implemented your suggestion for ``model.__getattr__``. 

Thank you!

**Comment by aliparsai** [comment]
Ok then, I will refactor the mutators I've already written to use your functions. We probably need to organize our efforts during the meeting to avoid wasting time.

**Comment by AlexandreDecan** [comment]
I know, sorry for that. Sadly, Tom didn't warn you about the relative immaturity of Sismic. I see current stable version more as a prototype than a software/library. Notably, the ``model`` module strongly benefits from the "refactoring" I made today. 

I'll review the PR asap.

**Comment by AlexandreDecan** [comment]
(Forget what I said about ``type``, I need to sleep ^^)

**Comment by aliparsai** [comment]
I just added type as a measure of later debugging. I don't think I still know exactly what is needed for the later stages. The thing is, if we have some mutants, we can at least do some manual mutation testing first to see if we get encouraging results. That's why I rushed a bit to implement few mutation operators.

P.S. sleep is important! :+1:

**Comment by AlexandreDecan** [comment]
I understand that the PR was about ``Event.__getattr__``, not about the integration of ``Mutator``, right?

As  ``Event.__getattr__`` is now consistent, I suggest to close this PR, and to go on with mutation testing on a dedicated branch (not on master) until we get something consistent and ready to be released.

**Comment by aliparsai** [comment]
Agreed.

**Pull request closed without merging**
