### PR TITLE
Add an asynchronous runner

### PR DESCRIPTION
**Pull request by AlexandreDecan**
This PR merely replaces `run_in_background` helper and introduces a new `runner` module with an `AsyncRunner` class that can be used to run an interpreter asynchronously. 

Here's the docstring of the runner: 

```python
    """
    An asynchronous runner that repeatedly execute given interpreter.

    The runner tries to call its `execute` method every `interval` seconds, assuming 
    that a call to interpreter `execute` method takes less time than `interval`. 
    If not, subsequent call is queued and will occur as soon as possible with
    no delay. The runner stops as soon as the underlying interpreter reaches 
    a final configuration.

    The execution must be started with the `start` method, and can be (definitively)
    stopped with the `stop` method. An execution can be temporarily suspended 
    using the `pause` and `unpause` methods. A call to `wait` blocks until 
    the statechart reaches a final configuration. 

    The current state of a runner can be obtained using its `running` and 
    `paused` properties.

    While this runner can be used "as is", it was designed to be subclassed and 
    as such, proposes several hooks to control the execution and additional 
    behaviours:

     - before_run: called (only once !) when the runner is started.
     - after_run: called (only once !) when the interpreter reaches a final configuration.
       configuration of the underlying interpreter is reached. 
     - execute: called at each step of the run. By default, call the `execute()`
       method of the underlying interpreter. 
     - before_execute: called right before the call to `execute()`;
     - after_execute: called right after the call to `execute()`.
       This method is called with the returned value of `execute()`.
       
    :param interpreter: interpreter instance to run.
    :param interval: interval between two calls to `execute`
    """
```

### CODE REVIEW

**Comment by trulede** [comment]
Hi,

The Helpers were useful to figure out how to run Sismic, kind of a documentation. However it never made sense to use them since we have to adapt them to our specific needs. So they were useful even if we did not use them :wink:



What you have here, I would turn into a interactive debugger, this is already something I thought starting as a simple Helper that would run a Sismic chart in a single line of code:

```
from sismic.helper import run_easy
run_easy('some.yaml')
```

and then evolve that to a debugger, which is quite similar to what you have:

```
from sismic.helper import debugger
sd = debugger
sd.load(filename="some.yaml")
sd.attach(filename="property.yaml")
sd.bind(filename="partner.yaml")
sd.bind(some_statechart_instance)
sd.set_breakpoint("state_name")
sd.set_breakpoint("event_name)

sd.run()
sd.stop()
sd.step()
sd.event(some_event)

sd.reload() <- reload all charts from disk, to pickup edits
sd.reset() <- start again

sd.stack() <-details for the current state, events it will react too, parent states and so on

```

Helpers are a good learning tool, and perhaps the runner is the basis for a debugger (which is something we would start working on anyway to assist our development).

**Comment by trulede** [comment]
It might also be worth considering a YAML format which references other YAML files, as a kind of a strategy or loader shortcut. But, we don't always work from a filesystem! so we should use some URI schema.

```
strategy:
  - statechart: file/somefile.yaml
     runner: sismic.runner.fred   # we will use our own runners/helpers, so use the full spec
     clock: ourlibrary.clock.redisclock # here we use our own clock
         - config:
            - redis_url = redis//localhost
     properties:
        - statechart: redis/somechart     # we would need to plugging a redis loader class, so this is just conceptual
        - statechart: zookeeper/somechart # same for zookeeper, conceptual only.
    bound:
       -statechart: file//someotherchart.yaml
     
```
and so on. the load the strategy, or application, of complex_model:

```
s = sismic.helper.strategy(strategy.yaml)
sd = sismic.helper.debugger(s)
sd.run()

```
This might be outside your scope, but I share it anyway.

**Comment by AlexandreDecan** [comment]
> Helpers are a good learning tool, and perhaps the runner is the basis for a debugger (which is something we would start working on anyway to assist our development).

Having a statechart debugger is something we also wanted at the very beginning. Then, I somehow arbitrarily decided that `pdb` is sufficient for most needs, but now that we have the more general *runner* thing, it could indeed be the right time to start thinking about how to properly implement a kind of *debugger*. 

First, I would like to implement two new runners (an event-based runner that continuously jumps to the next event, if any; and a synchronized runner that could be used to run concurrent statecharts). Because of this, I'll need to think on the API of a `Runner` base-class that could be reused for different runner. I hope to have some time to do it next week (I first need to finish #73 with a proper `EventQueue` class).

After that, I'll try to implement a `Debugger` that allows breakpoints to be specified. Probably that this runner will rely on the meta-events (used for property statecharts). That shouldn't be that difficult ;)

---

> It might also be worth considering a YAML format which references other YAML files, as a kind of a strategy or loader shortcut. But, we don't always work from a filesystem! so we should use some URI schema.

I agree it could be nice to have such support, but I think it's indeed out of the scope of Sismic. 

---

Another thing that I would like to change is the way we defined hooks and "notifications". Basically, in the current implementation, we have many direct hooks (like the many methods of `PythonEvaluator` that are called by the interpreter at specific points), "indirect hooks" (like the meta-events to support property statecharts) and "observable objects" (like the clock, the event queue, the trace, etc.). I would like to have a more uniform approach to deal with all these "hooks", and I'm currently looking into a signal-based communication between components (e.g. the interpreter defines signals like *before execute*, *before step*, after execute*, *on state entered*, *on consumed event*, etc., and other components can subscribe to those signals and attach callbacks to them). This will greatly simplify many parts of the current implementation, but will also contain a lot of breaking changes, e.g.:

 - Property statecharts could be implemented as a subclass of `Interpreter`, with an additional method `listen(other_interpreter)` that subscribes and reacts to these signals. As such, an observed interpreter won't know it's currently observed (which is something one can expect. In the current implement, the observed interpreter "attaches" property statecharts);
 - Bound callables could subscribe to the *event sent* signal. Similarly, the binding process will be inverted: a statechart will "listen" to another statechart, instead of binding a "listening statechart" to the current interpreter;
 - Clock could generates a *time changed* signal so that a `ClockBasedRunner` could listen to a clock and executes the statechart accordingly.
 - A debugger will simply listen to (nearly all) signals;
 - Event-based runner could subscribe to the `event queued` signal to jump to the next event;
 - An code evaluator won't have to implement such a complex interface (execute_on_entry and execute_on_exit were introduced only because we needed to be notified when a state is entered or exited);
 - ...

Given the breaking nature of these changes, I'll reserve them for Sismic 2.0.0, and I'm currently considering to wait for Sismic 2.0.0 to release transition priorities, clock-based time handling, new runners and delayed events (so I can benefit from the new signal-based hooks). But first, I'll achieve PR's #71, #72 and #73 and merge them into master ;)

**Comment by AlexandreDecan** [comment]
I've just opened an issue to discuss about the signal-based hooks. I suggest that we use the thread of #74 to discuss about them, and that we keep this discussion focused on (async & co) runners.

**Comment by trulede** [comment]
OK, but take it easy :wink: 

So far the we look like using is a Clock() and a simple tick/tock callback around MacroStep and a finalise which we can do with a few lines of code The async stuff, as a basis for a debugger is awesome, but otherwise ... it could end up being too hard :laughing:

There might be a more Pythonic way to do this stuff, decorators and so on. I've had a bit of a look, for ideas .. the on_before and on_after is soooo 1990's Microsoft ... there must be a really cool Python way to do it.

**Comment by trulede** [comment]
You know, somehow a notify decorator, where the caller provides the wrapper for the called/observed function, and that has the before and after code in it. A bit like how `yield` works.

**Comment by AlexandreDecan** [comment]
I prefer to avoid the use of a decorator because it's not a "per-instance" approach. I'll probably go for a general `hook` function that decorates a target on-the-fly (that's actually something I did in the `log_trace` function, but not in a very elegant way ;)

**Pull request merged**
