### PR TITLE
Refactor binding mechanism to support more use cases

### PR DESCRIPTION
**Pull request by AlexandreDecan**
(Inspired by @trulede's #87)

The new binding mechanism relies on ``attach`` and ``detach`` methods of an interpreter. The former can be used to attach a callable to an interpreter. This callable will be notified (i.e. called) for each meta-event sent by the interpreter. 

The ``bind`` and ``bind_property_statechart`` are implemented on top of this new mechanism. The idea is to wrap an interpreter (in the first case) or a property statechart (in the second case) with ``InternalEventListener`` and ``PropertyStatechartListener`` respectively. The former looks for "event sent" meta-events, and create an event instance for each of them. The second waits for a meta-event, queue it, then execute and check the property statechart.

### CODE REVIEW

**Comment by trulede** [comment]
I'm not really fond of this, sorry. 

The concept of an InternalEvent and PropertyChart is actually now spread over a few classes, which makes it frail. What is happening is when you change that behaviour, it breaks my implementation. And that situation will not change with this modification, unfortunately I just get same problems and limitations moved to another location.

That is why I wanted to separate the the Binding mechanism away from the Interpreter class. So that you can implement the behaviours you need for the core of Sismic, and other people with broader use cases can also implement their behaviours as needed.

Please keep in mind, the concept of InternalEvents and PropertyCharts, which are something that I understand as a core concept of Sismic as you develop it, are only the starting point for me. I also have a completely different interpretation of those same things depending on what I need to achieve.

That is why I propose a far more generic approach. The things I do don't listen to a Statechart ... they are in fact very active, they really are bound and tightly coupled.

**Comment by AlexandreDecan** [comment]
I don't understand. The implementation I proposed is less opinionated but still as generic as the one you suggested. Could you elaborate or provide an example? 

I also don't understand the point about "it breaks my implementation", notably because ``bind`` and ``bind_property_statechart`` (the two only ways to bind something in Sismic 1.3.0) are fully backwards compatible.

**Comment by trulede** [comment]
Yes, go ahead.

**Comment by AlexandreDecan** [comment]
Ok... That's not exactly the kind of feedback I expected 😁

**Pull request merged**
