### PR TITLE
A clock-based approach to deal with interpreter time

### PR DESCRIPTION
**Pull request by AlexandreDecan**
This PR deprecates `interpreter.time` and uses a clock-based approach to deal with time. 

A new class `Clock` is introduced. This class is used to create clocks that support both real and simulated time. By default, a clock relies on simulated time, and the time can be set by changing the value of `clock.time`. To rely on real time, one has to call `clock.start()`. Switching back to simulated time can be done with `clock.stop()`. Regardless of the notion of time that is currently used, the time value of a clock can be changed. Real time can be accelerated or slowed down by changing the `speed` attribute. 

The current time of an interpreter can still be retrieved using `interpreter.time`, but this attribute is now deprecated (warns a `DeprecationWarning`). The new API is `interpreter.clock` to retrieve its clock, and `interpreter.clock.time` to get or set current time value. 

When property statecharts are bound to an interpreter, they share its clock. This shouldn't have any incidence on existing code. 

However, the `run_in_background` helper was modified: it does **NO** longer automatically set the `time` value of an interpreter. To simulate the previous behaviour, one has to call `interpreter.clock.start()` before (or right after) passing the interpreter to the helper.

All these changes will ease the execution of statecharts that relies on wall-time clock, as it is now sufficient to call  `interpreter.clock.start()` before the first call to `execute` or `execute_once`. Previously, the time had to be manually set before each call to `execute` or `execute_once`.

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
I'll certainly make some other changes to the current implementation. What I've in mind:
 - Keep interpreter.time as the current time of the interpreter (will be based on the last lookup to clock.time);
 - Set interpreter.time = clock.time at the beginning of execute_once. In the current implementation, one can have a guard [time == 1] that evaluates to False and the resulting MacroStep.time that equals 1, because some time elapsed between guard evaluation and the creation of the step. I don't want that!

As a consequence, interpreter.time won't be deprecated when read (it will be deprecated when set, however. Time should be set on the clock, not on interpreter.time). I'll update code/test/doc tomorrow morning asap, but I've other unrelated things to do before that ;)

**Comment by trulede** [comment]
Hi,

I'm still reading though this. Just one first comment, do you think that it could be an idea to pass a Sismic.Clock() class as a parameter to Interpreter() when creating the instance. And of course having the parameter default value as your simulated time, and an included implementation for system/real time clock which can be passed as a parameter in my Use-Case.

I think the access would work the same as you have mentioned above. But Start() could then be called by execute/execute_once internally (if it would be needed, since I think is more selecting the clock).


That would allow people (i.e. me :wink: ) to implement clocks with esoteric time bases ... which is something I was asked about only this morning. It will present some interesting synchronisation capabilities between systems with different time bases.

Very nice. Will read and comment later today, or tomorrow ... got to bake a cake :laughing:

**Comment by trulede** [comment]
For a synchronisation to a esoteric time base. Assume a tick each 5mS, and then the Sismic Statechart perhaps takes 100mS to complete some task, with guards/after/idle all working from that 5 mS tick + some part of the 100mS working time.

Then the next 5mS tick comes in, and the whole timebase shifts back again to 5mS+5mS.

I'm not sure that is right, actually, perhaps the Clock() should simply update the Interpreter time each 5mS tick which comes in. The guards/after/idle would still work from that time base, only with a 5mS resolution.

The Clock() class implementation should be able to manage that. It could work. A Clock() interface, simple, two implementations in Sismic, and then let people like me create variations on that interface.

**Comment by trulede** [comment]
Hi,

a bit more time to think about this, I'm not sure if its too advanced .... the objective to explore here is to run Sismic from an external timebase. So, starting with this:

```
sc = import_from_yaml(filename="foobar.yaml")
it = Interpreter(sc, clock=RedisClock("redis://redis:6379")).execute_to_final()
```

The execute_to_final() then has a loop of calls to execute_once(), but, only calls that if the time has changed. So the Interpreter execution is actually controlled by the time source - stop the clock and the Interpreter will stop (at the next call to execute_oncel()).

The code behind that might look like this:

```
def RedisClock():
    self.tick_event = threading.Event()
    ....
    def on_redis_tick():
        self.tick_event.set() # set the clock tick event, see class threading.Event

    ....

def Interpreter(... clock=sismic_manual_clock() ...):
    self.clock = clock
    ....
    def execute_to_final():
        ....
        while not self.final:
            self.clock.tick_event.wait() # wait for clock tick event, see class threading.Event
            self.clock.tick_event.clear()
            self.time = self.clock.time()
            steps = self.execute_once()
```

And so, if the Redis clock is stopped, then Sismic Interpreter will stop too.


That is how I think a Clock() class could be pretty interesting in Sismic, and I can certainly help with implementation of the mechanism behind the so called execute_to_final (or execute_sync?).

**Comment by AlexandreDecan** [comment]
I think it's way too specific/advanced to be implemented or even shipped with Sismic :-) 

The purpose of the interpreter clock is to provide a time value that can be exposed to the `PythonCodeEvaluator` for `after` and `idle`. To summarize the rationale of this PR, the clock is used to manually or automatically provide a value to the current `interpreter.time` attribute. In the current implementation, it is not easy to have access to real-time clock (because we need to have a thread that continuously update `interpreter.time`). As a research prototype, one can expect this clock to be fully simulated (ie. manually set at each step). As a practical tool, one can also expect this clock to synchronize with real time. This is why the proposed implementation of `Clock` allows both, and even a combination of both, so we can freely start/stop the clock when needed.  With the new implementation, the clock is observed by the interpreter, and its value is used when needed (so there is no longer a need to continuously update the clock, hence the implementation based on `Clock._elapsed`). 

Based on your comments/feedback, I'll adapt current PR to support other clock classes (similarly to what can be done with `Evaluator` classes) and to have some kind of "callback" that is called before and after each execution of `execute_once` (so that you can quite easily keep track of the execution time, and adapt the time value returned by the clock accordingly). This will also help me to solve the issue raised in the second post of this thread. In short: I'll add two methods, namely `split` and `unsplit` that can be used to temporarily "freeze"/"unfreeze" the `time` attribute of the clock. When a MacroStep begins, the time will be frozen (so all guards and code will be evaluated/executed based on a single time value), and when the MacroStep ends, the clock will be unfrozen (meaning that its time value will potentially "jump" to the current time). If one wants to avoid the "processing time" of Sismic to be taken into account the clock, it will be sufficient to simply override the two methods to add a call to `self.stop` in `split` and a call to `self.start` in `unsplit`.

I expect the new implementation to help you by providing new ways to support your specific use case, but it will certainly require you to write some extra code. I agree it could be very interesting to have a kind of clock to "orchestrate" the interpreter (i.e. to call `execute` or `execute_once` at regular intervals, or at some specific moments), especially in a multi-threaded or distributed environment. From a pure architectural point of view, I think it's important that such an orchestrator manipulates the interpreter, and not the converse, as suggested in your code here above. Notably, the clock of such an orchestrator shouldn't be the same than the clock of an interpreter: these are two distinct concepts with distinct purposes. But that shouldn't prevent both clocks to be synchronized, especially given that the former (orchestrator clock) has control over the latter (interpreter clock).

**Comment by trulede** [comment]
Did I understand your comment regarding Orchestrator? In my example, the Redis Clock (Orchestrator) is manipulating the Interpreter. And its using the Event to signal the Interpreter that time has changed.

Where this gets quite interesting, is that the Clock is actually triggering the Interpreter, so you move this kind of code `time.sleep(delay)` (from run_in_background()) into the Clock class. Or, in your research Use Case, actually tick the Clock over manually. There is some potential there for us, I will look into that Event mechanism some more, to see if it is more reactive/accurate than time.sleep(). That I can put into my own helper, but never the less, if it works well you are welcome to take it too.


Yes, in the RedisClock() use case, we would discard the Processing Time of Sismic, but not in the "real-time" use case. So what you suggest is nice.

A meta class for Clock() (like the Evaluator interface) would be great, that would really open up possibilities. I think the people over here will be somewhat amazed at how such a mechanism can be utilised to solve distributed synchronisation. 


When you have the code ready, I can try to do a quick implementation of a custom Clock() class, and helper function, to see if I can manually tick the clock via Redis (or something else). In a distributed
environment, I suspect this will turn out to be a very big deal - the ability to stop/pause the entire system by simply impeding a "Redis Clock".

Thanks, let me know if you need contributions in any area relating to this.

**Comment by AlexandreDecan** [comment]
I pushed a new commit for this PR. Here are the main changes:

 - A new module ``sismic.clock`` with an abstract clock (``BaseClock``) subclasses by two different clocks: ``SimulatedClock`` (manual/automatic time, with speed support) and ``WallClock`` (a very simple proxy for ``time.time()``). 
 - ``Interpreter.__init__`` accepts a ``clock`` parameter, whose default is ``SimulatedClock()``. Notice that this parameter expects an **instance** of a clock, not a class/callable (we needed a class/callable for the ``Evaluator`` because of the dependency injection).
 - Any clock implementation must provide a ``time`` property (current exposed time), and two methods, namely ``split()`` and ``unsplit()`` that can be used to temporarily freeze the exposed time. These methods are used by the interpreter to freeze the time at the beginning of a step and to unfreeze the time at the end of the step. This is required if we want to stick with the *run-to-completion* semantics of UML.

**Comment by AlexandreDecan** [comment]
I'll certainly do some other changes, because in the current implementation (based on `split` and `unsplit`), there could be a race condition when multiple interpreters are executed in different thread with a shared clock (the first one being executed will `unsplit` the clock even if the other ones are still relying on the "frozen" property of the clock for their own execution). 

Consequently, I'll reintroduce `interpreter.time` as the time of the (beginning of the) last execution. That way, each interpreter will have its own "execution time", even if they share a common clock. As a consequence, that means that both `split` and `unsplit` are no longer needed and will be removed. Considering the use case of having a clock that does not take into account processing time, I suggest to subclass the interpreter and to override the `execute_once` method as follow:
```
def execute_once(self, *args, **kwargs):
  self.clock.stop()
  super().execute_once(*args, **kwargs)
  self.clock.start()
```

Obviously, in that case, the clock shouldn't be shared between different interpreters if they are run in separate threads.

**Comment by trulede** [comment]
OK. 

What I would like to try is write a Clock class which will run the clock portion in a Thread. It will update clock.time whenever the clock source ticks over. Then it should be possible for the Interpreter to call clock.time at the various points - i.e. before MacroStep, after the evaluation of "on entry" and so on.

I will take your suggestion, to implement a Interpreter, and also add some Events, in such a way that I can tick the whole thing over from the external clock source ... and get feedback when execute_once() completes so that the clock source knows to do the next "tick" (callback or Event, not sure which mechanism to use ATM).

Getting "run to completion" working over several distributed Statecharts, and synchronously, with a simulated timebase. That's really something interesting.


BTW, I've been using my Sismic model in our distributed environment for  a few weeks now, its linked into unit tests and gets lots of exercise. So far, no problems what so ever.

Its very low hassle to use and update with the Python and Yaml! Cool stuff.

**Comment by AlexandreDecan** [comment]
I'm glad to see that our research prototype has found (happy) users in the industry ;-)

Keep me informed. As soon as you confirm the current implementation in this PR is good for you, I'll merge it into master and release Sismic 1.3.0.

**Comment by trulede** [comment]
Working though it now...

Suggest to rename WallClock() to UtcClock().

... so far so good, will try to implement an asynchronous clock (i.e. in a thread) now.

**Comment by AlexandreDecan** [comment]
Indeed, it's more adequate to have UtcClock than WallClock. I made the change.

**Comment by trulede** [comment]
OK, this is great.

I find the BaseClock() name awkward too, if Clock() worked I would just use that (for consistency with other modules).

What follows is 2 examples.

**FooClock and FooInterpreter** - this is a realtime/utc clock with specified resolution. The clock runs in a Thread, so the Interpreter is free to do as it pleases (sleeps or whatever).

**BarClock and BarInterpreter** - this one runs synchronously between the Clock and Interpreter, on its own time-base, with no sleeps() or calls to time() ... so it runs as fast as it can :-)

Those two are the basis for a distributed clocking environment which is keeping with "run to completion" behavior.

**Comment by trulede** [comment]
Foo Clock():

```
from sismic.io import import_from_yaml
from sismic.interpreter import Interpreter
from sismic.clock import BaseClock

from threading import Thread


from time import time, sleep
import pprint

pp = pprint.PrettyPrinter(indent=4, width=120)



class FooClock(BaseClock):
    def __init__(self, resolution: float, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._time = 0.0
        self._resolution = resolution
        self._clock = None
        self._stop = 0

    def clock(self, clock_ref):
        while self._stop == 0:
            sleep(clock_ref._resolution)
            clock_ref._time += clock_ref._resolution

    def start(self):
        if self._clock is None:
            self._stop = 0
            self._clock = Thread(target = self.clock, args = (self, ))
        if not self._clock.is_alive():
            self._time = 0.0
            self._clock.start()
            while not self._clock.is_alive():
                pass

    def stop(self):
        self._stop = 1
        if self._clock and self._clock.is_alive():
            self._clock.join(timeout=self._resolution*10)
        self._clock = None

    @property
    def time(self):
        self.start()
        return self._time

    def __repr__(self):
        return 'FooClock[{}]'.format(self.time)

    def __del__(self):
        self.stop()


class FooInterpreter(Interpreter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def execute_once(self, *args, **kwargs):
        print("Foo Time: {:.6f}".format(self.clock.time))
        return super().execute_once(*args, **kwargs)

    def execute_to_final(self):
        while not self.final:
            steps = self.execute_once()
            if steps:
                pp.pprint(steps)
            sleep(0.1) # Just to keep the Foo Time printing to a minimum.

        self.clock.stop()


# Do it!
sc = import_from_yaml(filepath="./clock_test.yaml")
it = FooInterpreter(sc, clock=FooClock(resolution=0.005))
it.execute_to_final()
```

**Comment by trulede** [comment]
Bar Clock()

```
from sismic.io import import_from_yaml
from sismic.interpreter import Interpreter
from sismic.clock import BaseClock

from threading import Thread, Event


from time import time, sleep
import pprint

pp = pprint.PrettyPrinter(indent=4, width=120)



class BarClock(BaseClock):
    def __init__(self, timebase: float, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._time = 0.0
        self._timebase = timebase
        self._clock = None
        self._tick = Event()
        self._tock = Event()
        self._tock_timeout = 0.1
        self._stop = 0

    def clock(self, clock_ref):
        while self._stop == 0:
            self._tick.set()
            while self._tock.wait(timeout=self._tock_timeout) == False:
                if self._stop:
                    return
            self._tock.clear()
            clock_ref._time += clock_ref._timebase

    def start(self):
        if self._clock is None:
            self._stop = 0
            self._tick.clear()
            self._tock.clear()
            self._clock = Thread(target = self.clock, args = (self, ))
        if not self._clock.is_alive():
            self._time = 0.0
            self._clock.start()
            while not self._clock.is_alive():
                pass

    def stop(self):
        self._stop = 1
        if self._clock and self._clock.is_alive():
            self._clock.join(timeout=self._tock_timeout*10)
        self._clock = None

    @property
    def time(self):
        self.start()
        return self._time

    @property
    def tick(self):
        return self._tick

    @property
    def tock(self):
        return self._tock

    def __repr__(self):
        return 'BarClock[{}]'.format(self.time)

    def __del__(self):
        self.stop()


class BarInterpreter(Interpreter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def execute_once(self, *args, **kwargs):
        print("Bar Time: {:.6f}".format(self.clock.time))
        return super().execute_once(*args, **kwargs)

    def execute_to_final(self):
        while not self.final:
            if self.clock.tick.wait():
                self.clock.tick.clear()
                steps = self.execute_once()
                if steps:
                    pp.pprint(steps)
                self.clock.tock.set()

        self.clock.stop()


# Do it!
sc = import_from_yaml(filepath="./clock_test.yaml")
it = BarInterpreter(sc, clock=BarClock(timebase=0.1))
it.execute_to_final()
```

**Comment by trulede** [comment]
Thanks!

**Comment by trulede** [comment]
If could be possible to add a pair of methods to the BaseClock() which are called before and after the execute(once), then it would probably not even be necessary to make a custom Interpreter class.

def tick() called on entry to execute_once()

def tock() called on exit to execute_once()

and perhaps

def finalize() when the clock object is "discarded", i.e. the final state.


... that is just a thought ...

**Comment by AlexandreDecan** [comment]
I'll rename BaseClock to Clock, to be coherent with other base classes in Sismic (e.g. Evaluator).

I don't think a clock should be "interpreter-aware", unless it acts as an orchestrator. For this reason, I prefer not to add callbacks/hooks on a Clock/Interpreter. 

Looking at your code, I think it's not a good idea to have a `execute_to_final` method in the subclassed interpreter. It's better to have this function outside of an interpreter, e.g. like the `run_in_background` helper provided by Sismic. That way, you can call `execute_once` from your helper when it's convenient w.r.t. to an external clock and even do synchronization or manipulation of the internal clock of an interpreter (e.g. calling `interpreter.clock.stop()` before the `interpreter.execute_once()`, and then `interpreter.clock.start()` after). This removes the need to have specific callbacks.

**Comment by trulede** [comment]
Don't worry too much about the examples, its just to give you a feedback, to see the Clock working with Threads & Events, and what we can do with it. I'm very lazy ... just enough to prove the concept, then we think about it for a few days and weeks, and then refactor.

There is a certain benefit to implementing the entire clock function in a single class, and not having to create a new Interpreter or Helper for each specialisation. At least from my experience the clock() has a very specific lifecycle; before a MacroStep, after a MacroStep, and when the Final state is reached - regardless of the behaviour/nature of the clock.

So, in any case, I have to do it :wink: ... but it would be nice not to have to.


Generally, be be able to implement a clock with using sleep() is a _big_ deal. When we have lots of Sismic Models running, all at a 5 mS, and all hammering the system with sleep() calls ... this will be a big deal for us.

Thanks again.

**Comment by AlexandreDecan** [comment]
To avoid a Python `sleep`-based implementation, I suggest to rely on `threading.Timer` or even the low-level `signal` library (maybe not the best option, though). 

```python
def run(e, interpreter, delay):
    interpreter.execute()  # Or execute_once if explicitly required!
    if not e.is_set():
        threading.Timer(delay, run, [e, interpreter, delay]).start()

e = threading.Event()
interpreter = ...
delay = 0.05
run(e, interpreter, delay)
``` 

A call to `e.set()` terminates the "loop". 

If you want to explicitly deduce the processing time, I think this should do the trick:

```python
def run(e, interpreter, delay):
    start_time = time.time()
    interpreter.execute()
    elapsed = time.time() - start_time()
    if not e.is_set():
        threading.Timer(delay - elapsed, run, [e, interpreter, delay]).start()
```

You can even `stop()` and `start()` the clock (`SimulatedClock`) before and after each call to `execute()`.

**Comment by AlexandreDecan** [comment]
I looked at the implementation of `threading.Timer`. it's based on `Event`, which in turns is based on `_Condition` which makes use of... `sleep`.

**Comment by trulede** [comment]
:wink: when you peel away the layers of the onion, pretty much everything with threading is implemented with mutex's and sleep. I would like to hope that Python is optimising the underlying threading mechanism ... but somehow I doubt it.

Never-the-less, what your Clock() class, plus a few callbacks (tick/tock/finalize) does, is allow us to implement complex clocking mechanisms in the Clock() class while letting Sismic Models run without any real awareness of the clock timebase.

I think we (us, not you) can combine the Clock() with Notify(), with our distributed fabric (Redis etc) such that we only "tick" a Statechart when there is work for it to do. That will take some modifications to idle/after so that guard conditions can request a tick at the point in the future where they would evaluate True. 

And we can do other things too, like delay ticks to one Sismic Model out of a distributed group, so see how the overall system handles latency, or even swap the Clock() class in real-time to somehow change the behaviour of one particular Sismic Model, again to confirm the system behaviour under such a condition.

Lots of possibilities can be realised now. Its certainly a significant new capability.

**Comment by AlexandreDecan** [comment]
I know it won't really solve your problem, but what do you think of #72 ? It's supposed to be a replacement of `run_in_background` with more capabilities (notably due to the presence of many hooks). 

I know I told you I wanted to release 1.3.0 "asap", but I've other things that I would like to add to Sismic first. So I'll delay next release a little bit ;)

**Comment by AlexandreDecan** [comment]
Ok, I made a PR for the changes I would like to include in the next release. 
Could you please have a look at #73 ? I'm open to suggestions. I think that's something you also wanted to have in Sismic, right?

**Pull request merged**
