### PR TITLE
Issue #91 - Duplicate transitions after copying from another statechart

### PR DESCRIPTION
**Pull request by jnwtr**

### CODE REVIEW

**Comment by AlexandreDecan** [comment]
Thank you for this change! I'll release 1.4.2 in a few minutes, as soon as Travis ends.

**Comment by AlexandreDecan** [comment]
Murphy's law applied when deploying to PyPI. I'll have a look this afternoon. I'll keep you informed.

**Comment by jnwtr** [comment]
No thanks. I’m happy to contribute at least something to this beautiful piece of work.

**Comment by AlexandreDecan** [comment]
Release 1.4.2 is now deployed on PyPI ;)

**Pull request merged**
